name: CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            eval `ssh-agent`
            ssh-add ${{ secrets.SSH_GITHUBKEY_PATH }}
            cd /var/git/deploytest/
            git pull
            cp -r /var/git/deploytest/build/* /var/www/deploytest
